version: '3.8'

services:
  studymama-ui:
    image: studymama-ui:latest
    hostname: studymama-ui
    container_name: studymama-ui
    networks:
      - studymama_default
    ports:
      - "8000:8000"
    environment:
      API_URL: http://studymama-load-balancer-795957589.ap-southeast-1.elb.amazonaws.com:8080
      STUDYMAMA_UI: http://localhost:8080
      CONTENT_URL: http://www.facebook.com

networks:
  studymama_default:
    driver: "bridge"
