version: '3.8'

services:
  studymama-ui:
    image: studymama-ui:latest
    hostname: studymama-ui
    container_name: studymama-ui
    networks:
      - studymama_default
    ports:
      - "8001:8001"

networks:
  studymama_default:
    driver: "bridge"
